### ISSUE TITLE
Suggestion for stitching library

### ISSUE THREAD

**Issue by jouko-kelomaki** [jarsba/meow#1]
Opencv looks promising and [this tutorial](https://docs.opencv.org/4.5.2/d8/d19/tutorial_stitcher.html) seems close to the actual goals (as far as I understand them). The library has python bindings. I might try out the tutorial later this weekend, but let me know if you have other plans for the project, so I won't attempt an already solved problem.

**Comment by jarsba** [comment]
That OpenCV Stitcher-class looks good. I might continue working on the project before the weekend, but I can also work with video synchronization or do part of the Stitcher-class. My idea for the first version was to be able to produce a watchable panorama video out of two 10s clips from both cameras. Let me know if you need video material. My broad idea was to stitch frames together one by one and produce a new video out of a bunch of panorama images. I could not find many examples of video-stitching, but it might be doable also.

I saved these resources during research related to the video stitching:

https://www.pyimagesearch.com/2016/01/25/real-time-panorama-and-image-stitching-with-opencv/
https://towardsdatascience.com/image-panorama-stitching-with-opencv-2402bde6b46c
https://github.com/krutikabapat/Video-Panorama
https://kushalvyas.github.io/stitching.html
https://www.pyimagesearch.com/2018/12/17/image-stitching-with-opencv-and-python/
http://datahacker.rs/005-how-to-create-a-panorama-image-using-opencv-with-python/
